export type Artifact = {
  slug: string;
  name: string;
  version: string;
  domain: 'DeFi' | 'Cybersec';
  trust: number;
  te: number;
  status: 'SAFE';
  verified: string;
  description: string;
  publisher: string;
  license: string;
  installCount: number;
  tags: string[];
};

const DEFI_ARTIFACTS: Artifact[] = [
  { slug: 'defi-whale-detector', name: 'defi-whale-detector', version: 'v2.0', domain: 'DeFi', trust: 98, te: 14.1, status: 'SAFE', verified: '2h ago', description: 'Detects and classifies whale wallet activity across DeFi protocols. Tracks accumulation patterns, wash trading, and coordinated movements. Trained on 18 months of on-chain data across Ethereum, Arbitrum, and Solana.', publisher: 'sentinel-labs', license: 'Apache-2.0', installCount: 2847, tags: ['whale-detection', 'on-chain', 'risk'] },
  { slug: 'defi-risk-assessment', name: 'defi-risk-assessment', version: 'v2.1', domain: 'DeFi', trust: 97, te: 13.8, status: 'SAFE', verified: '2h ago', description: 'Expert-calibrated risk scoring for DeFi protocols. Trained on 20 protocols across lending, bridges, yield aggregators, and stablecoins. Cross-model validated on GPT-4o and Claude Sonnet.', publisher: 'sentinel-labs', license: 'MIT', installCount: 3241, tags: ['risk-scoring', 'lending', 'bridges'] },
  { slug: 'defi-yield-optimizer', name: 'defi-yield-optimizer', version: 'v1.3', domain: 'DeFi', trust: 95, te: 12.9, status: 'SAFE', verified: '3h ago', description: 'Yield strategy evaluation and optimization for DeFi vaults. Compares APY sustainability, impermanent loss risk, and protocol solvency across yield farming strategies.', publisher: 'neuroforge', license: 'MIT', installCount: 1892, tags: ['yield', 'farming', 'optimization'] },
  { slug: 'defi-apy-calculator', name: 'defi-apy-calculator', version: 'v2.2', domain: 'DeFi', trust: 94, te: 12.6, status: 'SAFE', verified: '4h ago', description: 'Accurate APY/APR calculation engine for complex DeFi positions. Handles compounding, fee structures, and token emissions schedules across 50+ protocols.', publisher: 'meridian-ai', license: 'MIT', installCount: 1654, tags: ['apy', 'calculation', 'analytics'] },
  { slug: 'defi-protocol-scanner', name: 'defi-protocol-scanner', version: 'v1.0', domain: 'DeFi', trust: 93, te: 12.1, status: 'SAFE', verified: '5h ago', description: 'Automated smart contract risk analysis. Scans for known vulnerability patterns, centralization risks, and upgrade proxy configurations.', publisher: 'cipher-collective', license: 'Apache-2.0', installCount: 1423, tags: ['smart-contracts', 'audit', 'scanning'] },
  { slug: 'defi-swap-router', name: 'defi-swap-router', version: 'v1.6', domain: 'DeFi', trust: 93, te: 12.2, status: 'SAFE', verified: '5h ago', description: 'Multi-DEX routing optimizer. Finds optimal swap paths across Uniswap, Curve, Balancer, and aggregators with MEV-aware slippage estimation.', publisher: 'sentinel-labs', license: 'MIT', installCount: 1387, tags: ['dex', 'routing', 'swaps'] },
  { slug: 'defi-liquidity-monitor', name: 'defi-liquidity-monitor', version: 'v0.9', domain: 'DeFi', trust: 92, te: 11.7, status: 'SAFE', verified: '6h ago', description: 'Real-time liquidity depth monitoring for DeFi pools. Alerts on significant liquidity removals and identifies shallow markets.', publisher: 'neuroforge', license: 'CC-BY-4.0', installCount: 1105, tags: ['liquidity', 'monitoring', 'pools'] },
  { slug: 'defi-governance-tracker', name: 'defi-governance-tracker', version: 'v1.2', domain: 'DeFi', trust: 91, te: 11.4, status: 'SAFE', verified: '8h ago', description: 'DAO governance proposal tracking and impact analysis. Classifies proposals by category, estimates treasury impact, and flags contentious votes.', publisher: 'meridian-ai', license: 'MIT', installCount: 987, tags: ['governance', 'dao', 'proposals'] },
  { slug: 'defi-staking-optimizer', name: 'defi-staking-optimizer', version: 'v1.4', domain: 'DeFi', trust: 91, te: 11.3, status: 'SAFE', verified: '9h ago', description: 'Staking strategy comparison across PoS networks and liquid staking derivatives. Accounts for slashing risk, lock-up periods, and MEV rewards.', publisher: 'cipher-collective', license: 'MIT', installCount: 934, tags: ['staking', 'pos', 'liquid-staking'] },
  { slug: 'defi-bridge-validator', name: 'defi-bridge-validator', version: 'v0.8', domain: 'DeFi', trust: 90, te: 11.0, status: 'SAFE', verified: '10h ago', description: 'Cross-chain bridge security assessment. Evaluates validator sets, multisig configurations, TVL concentration, and historical exploit patterns.', publisher: 'sentinel-labs', license: 'Apache-2.0', installCount: 876, tags: ['bridges', 'cross-chain', 'security'] },
  { slug: 'defi-portfolio-rebalancer', name: 'defi-portfolio-rebalancer', version: 'v1.3', domain: 'DeFi', trust: 90, te: 11.1, status: 'SAFE', verified: '11h ago', description: 'Portfolio rebalancing recommendations for DeFi positions. Considers gas costs, slippage, and correlation analysis for optimal allocation.', publisher: 'neuroforge', license: 'MIT', installCount: 823, tags: ['portfolio', 'rebalancing', 'allocation'] },
  { slug: 'defi-token-classifier', name: 'defi-token-classifier', version: 'v1.5', domain: 'DeFi', trust: 89, te: 10.8, status: 'SAFE', verified: '12h ago', description: 'Token classification and risk categorization. Identifies token types, detects honeypot contracts, and assesses tokenomics sustainability.', publisher: 'cipher-collective', license: 'MIT', installCount: 756, tags: ['tokens', 'classification', 'honeypot'] },
  { slug: 'defi-rug-pull-detector', name: 'defi-rug-pull-detector', version: 'v1.1', domain: 'DeFi', trust: 88, te: 10.5, status: 'SAFE', verified: '14h ago', description: 'Early warning system for rug pull indicators. Monitors deployer wallet patterns, liquidity lock status, and contract permission flags.', publisher: 'sentinel-labs', license: 'Apache-2.0', installCount: 712, tags: ['rug-pull', 'scam-detection', 'early-warning'] },
  { slug: 'defi-vault-scanner', name: 'defi-vault-scanner', version: 'v1.2', domain: 'DeFi', trust: 88, te: 10.6, status: 'SAFE', verified: '13h ago', description: 'Vault strategy analysis and risk decomposition. Breaks down complex vault strategies into component risks and estimates max drawdown scenarios.', publisher: 'meridian-ai', license: 'MIT', installCount: 689, tags: ['vaults', 'strategy', 'risk'] },
  { slug: 'defi-oracle-validator', name: 'defi-oracle-validator', version: 'v1.1', domain: 'DeFi', trust: 87, te: 10.3, status: 'SAFE', verified: '15h ago', description: 'Oracle reliability and manipulation resistance assessment. Tests price feed freshness, deviation thresholds, and multi-source redundancy.', publisher: 'cipher-collective', license: 'CC-BY-4.0', installCount: 634, tags: ['oracles', 'price-feeds', 'manipulation'] },
  { slug: 'defi-flash-loan-monitor', name: 'defi-flash-loan-monitor', version: 'v1.0', domain: 'DeFi', trust: 86, te: 10.1, status: 'SAFE', verified: '16h ago', description: 'Flash loan attack detection and pattern recognition. Identifies suspicious transaction sequences and multi-protocol attack vectors.', publisher: 'sentinel-labs', license: 'Apache-2.0', installCount: 598, tags: ['flash-loans', 'attacks', 'detection'] },
  { slug: 'defi-liquidation-alert', name: 'defi-liquidation-alert', version: 'v1.1', domain: 'DeFi', trust: 86, te: 10.0, status: 'SAFE', verified: '17h ago', description: 'Liquidation risk monitoring for lending positions. Tracks health factors, collateral volatility, and cascade liquidation scenarios.', publisher: 'neuroforge', license: 'MIT', installCount: 567, tags: ['liquidation', 'lending', 'health-factor'] },
  { slug: 'defi-tvl-tracker', name: 'defi-tvl-tracker', version: 'v1.3', domain: 'DeFi', trust: 85, te: 9.7, status: 'SAFE', verified: '18h ago', description: 'TVL tracking and flow analysis across DeFi protocols. Detects capital rotation patterns, identifies growing protocols, and flags TVL manipulation.', publisher: 'meridian-ai', license: 'MIT', installCount: 523, tags: ['tvl', 'capital-flows', 'analytics'] },
  { slug: 'defi-collateral-tracker', name: 'defi-collateral-tracker', version: 'v1.1', domain: 'DeFi', trust: 84, te: 9.5, status: 'SAFE', verified: '20h ago', description: 'Collateral quality and concentration monitoring. Tracks collateral ratios, correlated assets, and de-peg risk across lending markets.', publisher: 'cipher-collective', license: 'MIT', installCount: 478, tags: ['collateral', 'lending', 'de-peg'] },
  { slug: 'defi-gas-optimizer', name: 'defi-gas-optimizer', version: 'v0.9', domain: 'DeFi', trust: 83, te: 9.2, status: 'SAFE', verified: '1d ago', description: 'Gas cost optimization for DeFi transactions. Estimates optimal gas prices, suggests batching opportunities, and identifies low-fee windows.', publisher: 'neuroforge', license: 'MIT', installCount: 445, tags: ['gas', 'optimization', 'costs'] },
  { slug: 'defi-impermanent-loss', name: 'defi-impermanent-loss', version: 'v0.7', domain: 'DeFi', trust: 82, te: 8.9, status: 'SAFE', verified: '1d ago', description: 'Impermanent loss calculator and predictor for AMM positions. Supports concentrated liquidity ranges and multi-asset pools.', publisher: 'meridian-ai', license: 'CC-BY-4.0', installCount: 412, tags: ['impermanent-loss', 'amm', 'concentrated-liquidity'] },
  { slug: 'defi-slippage-guard', name: 'defi-slippage-guard', version: 'v1.0', domain: 'DeFi', trust: 81, te: 8.6, status: 'SAFE', verified: '1d ago', description: 'Slippage estimation and protection for large trades. Simulates order impact across liquidity sources and suggests optimal execution strategies.', publisher: 'sentinel-labs', license: 'MIT', installCount: 389, tags: ['slippage', 'trading', 'execution'] },
  { slug: 'defi-pool-analyzer', name: 'defi-pool-analyzer', version: 'v1.0', domain: 'DeFi', trust: 80, te: 8.4, status: 'SAFE', verified: '2d ago', description: 'Liquidity pool composition and performance analysis. Evaluates fee generation, volume trends, and compares pool returns across protocols.', publisher: 'cipher-collective', license: 'MIT', installCount: 356, tags: ['pools', 'analysis', 'fees'] },
  { slug: 'defi-mev-analyzer', name: 'defi-mev-analyzer', version: 'v0.6', domain: 'DeFi', trust: 78, te: 7.8, status: 'SAFE', verified: '2d ago', description: 'MEV extraction pattern detection and quantification. Identifies sandwich attacks, frontrunning, and backrunning across DEX transactions.', publisher: 'neuroforge', license: 'Apache-2.0', installCount: 312, tags: ['mev', 'sandwich', 'frontrunning'] },
  { slug: 'defi-leverage-monitor', name: 'defi-leverage-monitor', version: 'v0.7', domain: 'DeFi', trust: 77, te: 7.5, status: 'SAFE', verified: '3d ago', description: 'System-wide leverage monitoring for DeFi. Aggregates open interest, margin ratios, and estimates cascade liquidation thresholds.', publisher: 'sentinel-labs', license: 'MIT', installCount: 278, tags: ['leverage', 'margin', 'systemic-risk'] },
  { slug: 'defi-dao-monitor', name: 'defi-dao-monitor', version: 'v0.8', domain: 'DeFi', trust: 76, te: 7.3, status: 'SAFE', verified: '3d ago', description: 'DAO health and activity monitoring. Tracks voter participation, proposal velocity, treasury diversification, and contributor activity.', publisher: 'meridian-ai', license: 'CC-BY-4.0', installCount: 245, tags: ['dao', 'health', 'treasury'] },
  { slug: 'defi-cross-chain-monitor', name: 'defi-cross-chain-monitor', version: 'v0.6', domain: 'DeFi', trust: 74, te: 6.9, status: 'SAFE', verified: '4d ago', description: 'Cross-chain message and asset flow monitoring. Tracks bridge throughput, message latency, and detects anomalous cross-chain patterns.', publisher: 'cipher-collective', license: 'MIT', installCount: 198, tags: ['cross-chain', 'bridges', 'monitoring'] },
  { slug: 'defi-fee-analyzer', name: 'defi-fee-analyzer', version: 'v0.5', domain: 'DeFi', trust: 72, te: 6.4, status: 'SAFE', verified: '5d ago', description: 'Protocol fee structure analysis and comparison. Benchmarks fee schedules, identifies hidden costs, and projects fee impact on yields.', publisher: 'neuroforge', license: 'MIT', installCount: 167, tags: ['fees', 'costs', 'comparison'] },
];

const CYBERSEC_ARTIFACTS: Artifact[] = [
  { slug: 'cybersec-vuln-scanner', name: 'cybersec-vuln-scanner', version: 'v2.0', domain: 'Cybersec', trust: 97, te: 13.9, status: 'SAFE', verified: '3h ago', description: 'Vulnerability severity scoring trained on 200+ real CVEs. CVSS-anchored with operational context adjustment and exploit likelihood estimation.', publisher: 'neuroforge', license: 'Apache-2.0', installCount: 2956, tags: ['vulnerabilities', 'cve', 'scoring'] },
  { slug: 'cybersec-threat-intel', name: 'cybersec-threat-intel', version: 'v1.4', domain: 'Cybersec', trust: 96, te: 13.4, status: 'SAFE', verified: '2h ago', description: 'Threat intelligence correlation and prioritization. Maps indicators to MITRE ATT&CK, scores threat relevance, and identifies campaign patterns.', publisher: 'sentinel-labs', license: 'MIT', installCount: 2734, tags: ['threat-intel', 'mitre', 'indicators'] },
  { slug: 'cybersec-endpoint-guard', name: 'cybersec-endpoint-guard', version: 'v1.5', domain: 'Cybersec', trust: 95, te: 13.1, status: 'SAFE', verified: '3h ago', description: 'Endpoint behavior analysis and anomaly detection. Identifies suspicious process trees, unusual file access patterns, and lateral movement indicators.', publisher: 'cipher-collective', license: 'MIT', installCount: 2145, tags: ['endpoint', 'behavior', 'anomaly'] },
  { slug: 'cybersec-zero-day-monitor', name: 'cybersec-zero-day-monitor', version: 'v1.2', domain: 'Cybersec', trust: 94, te: 12.5, status: 'SAFE', verified: '4h ago', description: 'Zero-day vulnerability early warning and impact assessment. Monitors disclosure channels, estimates blast radius, and recommends mitigations.', publisher: 'sentinel-labs', license: 'Apache-2.0', installCount: 1876, tags: ['zero-day', 'early-warning', 'disclosure'] },
  { slug: 'cybersec-traffic-analyzer', name: 'cybersec-traffic-analyzer', version: 'v1.3', domain: 'Cybersec', trust: 93, te: 12.3, status: 'SAFE', verified: '5h ago', description: 'Network traffic analysis and C2 detection. Identifies beaconing patterns, DNS tunneling, and encrypted channel anomalies.', publisher: 'neuroforge', license: 'MIT', installCount: 1654, tags: ['network', 'traffic', 'c2-detection'] },
  { slug: 'cybersec-malware-classifier', name: 'cybersec-malware-classifier', version: 'v1.2', domain: 'Cybersec', trust: 92, te: 11.8, status: 'SAFE', verified: '6h ago', description: 'Malware family classification and behavior prediction. Identifies ransomware, trojans, wipers, and infostealers from static and dynamic indicators.', publisher: 'cipher-collective', license: 'Apache-2.0', installCount: 1432, tags: ['malware', 'classification', 'ransomware'] },
  { slug: 'cybersec-container-scanner', name: 'cybersec-container-scanner', version: 'v1.4', domain: 'Cybersec', trust: 92, te: 11.9, status: 'SAFE', verified: '7h ago', description: 'Container image security scanning and misconfiguration detection. Checks for vulnerable base images, exposed secrets, and privilege escalation paths.', publisher: 'meridian-ai', license: 'MIT', installCount: 1389, tags: ['containers', 'docker', 'kubernetes'] },
  { slug: 'cybersec-log-analyzer', name: 'cybersec-log-analyzer', version: 'v1.3', domain: 'Cybersec', trust: 91, te: 11.5, status: 'SAFE', verified: '8h ago', description: 'Security log analysis and correlation engine. Detects brute force patterns, privilege escalation attempts, and data exfiltration indicators across SIEM data.', publisher: 'sentinel-labs', license: 'MIT', installCount: 1256, tags: ['logs', 'siem', 'correlation'] },
  { slug: 'cybersec-forensic-toolkit', name: 'cybersec-forensic-toolkit', version: 'v1.3', domain: 'Cybersec', trust: 91, te: 11.4, status: 'SAFE', verified: '9h ago', description: 'Digital forensics analysis assistance. Guides evidence collection, timeline reconstruction, and artifact analysis for incident investigation.', publisher: 'neuroforge', license: 'Apache-2.0', installCount: 1123, tags: ['forensics', 'investigation', 'evidence'] },
  { slug: 'cybersec-ransomware-detector', name: 'cybersec-ransomware-detector', version: 'v1.0', domain: 'Cybersec', trust: 90, te: 11.2, status: 'SAFE', verified: '9h ago', description: 'Ransomware behavior detection and classification. Identifies encryption patterns, ransom note indicators, and lateral propagation techniques.', publisher: 'cipher-collective', license: 'MIT', installCount: 1067, tags: ['ransomware', 'detection', 'encryption'] },
  { slug: 'cybersec-phishing-detector', name: 'cybersec-phishing-detector', version: 'v1.0', domain: 'Cybersec', trust: 89, te: 10.7, status: 'SAFE', verified: '10h ago', description: 'Phishing email and URL detection. Analyzes sender patterns, URL obfuscation, and content similarity to known phishing campaigns.', publisher: 'meridian-ai', license: 'MIT', installCount: 987, tags: ['phishing', 'email', 'url-analysis'] },
  { slug: 'cybersec-iam-auditor', name: 'cybersec-iam-auditor', version: 'v1.2', domain: 'Cybersec', trust: 88, te: 10.5, status: 'SAFE', verified: '13h ago', description: 'IAM policy analysis and least-privilege enforcement. Identifies over-permissioned roles, dormant accounts, and privilege escalation paths in cloud environments.', publisher: 'sentinel-labs', license: 'Apache-2.0', installCount: 923, tags: ['iam', 'cloud', 'least-privilege'] },
  { slug: 'cybersec-network-monitor', name: 'cybersec-network-monitor', version: 'v1.1', domain: 'Cybersec', trust: 88, te: 10.4, status: 'SAFE', verified: '12h ago', description: 'Network segmentation and access control monitoring. Validates firewall rules, detects unauthorized connections, and maps network exposure.', publisher: 'neuroforge', license: 'MIT', installCount: 878, tags: ['network', 'segmentation', 'firewall'] },
  { slug: 'cybersec-incident-response', name: 'cybersec-incident-response', version: 'v0.9', domain: 'Cybersec', trust: 87, te: 10.2, status: 'SAFE', verified: '14h ago', description: 'Incident response playbook assistance. Guides containment, eradication, and recovery procedures based on incident classification and severity.', publisher: 'cipher-collective', license: 'CC-BY-4.0', installCount: 834, tags: ['incident-response', 'playbooks', 'containment'] },
  { slug: 'cybersec-cert-validator', name: 'cybersec-cert-validator', version: 'v1.1', domain: 'Cybersec', trust: 87, te: 10.3, status: 'SAFE', verified: '15h ago', description: 'TLS certificate chain validation and configuration auditing. Checks for weak ciphers, expired certificates, and misconfigured HSTS policies.', publisher: 'meridian-ai', license: 'MIT', installCount: 789, tags: ['tls', 'certificates', 'configuration'] },
  { slug: 'cybersec-firewall-auditor', name: 'cybersec-firewall-auditor', version: 'v1.1', domain: 'Cybersec', trust: 86, te: 10.0, status: 'SAFE', verified: '16h ago', description: 'Firewall rule analysis and optimization. Identifies redundant rules, detects shadowed rules, and recommends rule consolidation.', publisher: 'sentinel-labs', license: 'MIT', installCount: 745, tags: ['firewall', 'rules', 'optimization'] },
  { slug: 'cybersec-siem-connector', name: 'cybersec-siem-connector', version: 'v1.0', domain: 'Cybersec', trust: 85, te: 9.8, status: 'SAFE', verified: '18h ago', description: 'SIEM integration and alert normalization. Maps diverse log sources to a unified schema and reduces alert fatigue through intelligent deduplication.', publisher: 'neuroforge', license: 'Apache-2.0', installCount: 698, tags: ['siem', 'alerts', 'normalization'] },
  { slug: 'cybersec-compliance-checker', name: 'cybersec-compliance-checker', version: 'v1.1', domain: 'Cybersec', trust: 85, te: 9.6, status: 'SAFE', verified: '19h ago', description: 'Compliance posture assessment against SOC 2, ISO 27001, and NIST frameworks. Maps controls to evidence and identifies gaps.', publisher: 'cipher-collective', license: 'MIT', installCount: 656, tags: ['compliance', 'soc2', 'nist'] },
  { slug: 'cybersec-honeypot-manager', name: 'cybersec-honeypot-manager', version: 'v1.0', domain: 'Cybersec', trust: 84, te: 9.4, status: 'SAFE', verified: '20h ago', description: 'Honeypot deployment strategy and attacker behavior analysis. Recommends placement, monitors interactions, and extracts TTPs from attacker sessions.', publisher: 'meridian-ai', license: 'CC-BY-4.0', installCount: 612, tags: ['honeypot', 'deception', 'ttp'] },
  { slug: 'cybersec-apt-tracker', name: 'cybersec-apt-tracker', version: 'v0.8', domain: 'Cybersec', trust: 83, te: 9.1, status: 'SAFE', verified: '1d ago', description: 'APT group tracking and attribution assistance. Correlates indicators with known threat actor toolkits and campaign infrastructure.', publisher: 'sentinel-labs', license: 'Apache-2.0', installCount: 567, tags: ['apt', 'attribution', 'threat-actors'] },
  { slug: 'cybersec-waf-tester', name: 'cybersec-waf-tester', version: 'v1.0', domain: 'Cybersec', trust: 83, te: 9.0, status: 'SAFE', verified: '1d ago', description: 'WAF rule testing and bypass detection. Validates rule coverage against OWASP payloads and identifies evasion techniques.', publisher: 'neuroforge', license: 'MIT', installCount: 534, tags: ['waf', 'testing', 'owasp'] },
  { slug: 'cybersec-dns-analyzer', name: 'cybersec-dns-analyzer', version: 'v0.9', domain: 'Cybersec', trust: 82, te: 8.8, status: 'SAFE', verified: '1d ago', description: 'DNS traffic analysis and threat detection. Identifies DGA domains, DNS tunneling, and suspicious resolver behavior.', publisher: 'cipher-collective', license: 'MIT', installCount: 489, tags: ['dns', 'dga', 'tunneling'] },
  { slug: 'cybersec-dlp-monitor', name: 'cybersec-dlp-monitor', version: 'v0.9', domain: 'Cybersec', trust: 81, te: 8.5, status: 'SAFE', verified: '1d ago', description: 'Data loss prevention monitoring and classification. Identifies sensitive data patterns, tracks data movement, and flags policy violations.', publisher: 'meridian-ai', license: 'MIT', installCount: 456, tags: ['dlp', 'data-protection', 'classification'] },
  { slug: 'cybersec-credential-scanner', name: 'cybersec-credential-scanner', version: 'v0.8', domain: 'Cybersec', trust: 80, te: 8.3, status: 'SAFE', verified: '2d ago', description: 'Credential exposure detection across code repositories, config files, and paste sites. Identifies API keys, tokens, and password patterns.', publisher: 'sentinel-labs', license: 'Apache-2.0', installCount: 423, tags: ['credentials', 'secrets', 'scanning'] },
  { slug: 'cybersec-supply-chain-audit', name: 'cybersec-supply-chain-audit', version: 'v0.7', domain: 'Cybersec', trust: 79, te: 8.1, status: 'SAFE', verified: '2d ago', description: 'Software supply chain security assessment. Analyzes dependency trees, checks for known compromised packages, and evaluates build pipeline integrity.', publisher: 'neuroforge', license: 'MIT', installCount: 389, tags: ['supply-chain', 'dependencies', 'sbom'] },
  { slug: 'cybersec-osint-collector', name: 'cybersec-osint-collector', version: 'v0.7', domain: 'Cybersec', trust: 76, te: 7.4, status: 'SAFE', verified: '3d ago', description: 'Open source intelligence collection and enrichment. Aggregates data from public sources, enriches indicators, and builds threat context.', publisher: 'cipher-collective', license: 'CC-BY-4.0', installCount: 312, tags: ['osint', 'intelligence', 'enrichment'] },
  { slug: 'cybersec-patch-validator', name: 'cybersec-patch-validator', version: 'v0.6', domain: 'Cybersec', trust: 75, te: 7.1, status: 'SAFE', verified: '4d ago', description: 'Patch validation and deployment risk assessment. Estimates compatibility impact, identifies breaking changes, and prioritizes patches by exploitability.', publisher: 'meridian-ai', license: 'MIT', installCount: 267, tags: ['patching', 'validation', 'prioritization'] },
  { slug: 'cybersec-pentest-framework', name: 'cybersec-pentest-framework', version: 'v0.5', domain: 'Cybersec', trust: 69, te: 5.7, status: 'SAFE', verified: '7d ago', description: 'Penetration testing methodology and checklist assistance. Guides reconnaissance, enumeration, and exploitation phases with PTES methodology alignment.', publisher: 'sentinel-labs', license: 'Apache-2.0', installCount: 198, tags: ['pentest', 'methodology', 'ptes'] },
];

export const ALL_ARTIFACTS: Artifact[] = [...DEFI_ARTIFACTS, ...CYBERSEC_ARTIFACTS];

export function getArtifactBySlug(slug: string): Artifact | undefined {
  return ALL_ARTIFACTS.find((a) => a.slug === slug);
}

export const VERIFIED_ORDER: Record<string, number> = {
  '2h ago': 2, '3h ago': 3, '4h ago': 4, '5h ago': 5, '6h ago': 6,
  '7h ago': 7, '8h ago': 8, '9h ago': 9, '10h ago': 10, '11h ago': 11,
  '12h ago': 12, '13h ago': 13, '14h ago': 14, '15h ago': 15, '16h ago': 16,
  '17h ago': 17, '18h ago': 18, '19h ago': 19, '20h ago': 20,
  '1d ago': 24, '2d ago': 48, '3d ago': 72, '4d ago': 96, '5d ago': 120,
  '7d ago': 168, '30d ago': 720,
};
