//! Background daemons — the librarian and the dreamer.
//!
//! The librarian runs every 5 minutes:
//!   1. Counts all documents, compares to last count
//!   2. Checks acquisitions/ for unsorted documents
//!   3. Removes expired ephemera (older than 1 day)
//!   4. Rebuilds the catalogue index cache
//!   5. Writes a journal entry
//!
//! The dreamer runs every hour:
//!   Reads random fragments, inscribes dream documents in ephemera/.

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::thread;
use std::time::{Duration, SystemTime};

use crate::library;

/// Start the librarian daemon. Returns a handle to stop it.
pub fn start_librarian(root: PathBuf, running: Arc<AtomicBool>) -> thread::JoinHandle<()> {
    thread::spawn(move || {
        let mut last_count: Option<usize> = None;

        // Wait 30 seconds before first run (let the reader settle in)
        thread::sleep(Duration::from_secs(30));

        while running.load(Ordering::Relaxed) {
            let count = count_documents(&root);
            let acquisitions = count_in(&root.join("acquisitions"));
            let expired = clean_ephemera(&root);

            // Compare to last count
            let change_note = match last_count {
                Some(prev) if count > prev => {
                    format!("{} new documents since last round.", count - prev)
                }
                Some(prev) if count < prev => {
                    format!("{} documents removed since last round.", prev - count)
                }
                _ => "No change in document count.".to_string(),
            };
            last_count = Some(count);

            // Write journal
            let mut notes = vec![
                format!("Librarian round: {count} documents total."),
                change_note,
            ];
            if acquisitions > 0 {
                notes.push(format!("{acquisitions} documents waiting in acquisitions."));
            }
            if expired > 0 {
                notes.push(format!("{expired} expired documents removed from ephemera."));
            }

            for note in &notes {
                library::journal_write(&root, note);
            }

            // Sleep 5 minutes, checking for shutdown every second
            for _ in 0..300 {
                if !running.load(Ordering::Relaxed) {
                    break;
                }
                thread::sleep(Duration::from_secs(1));
            }
        }
    })
}

/// Start the dreamer daemon. Returns a handle to stop it.
pub fn start_dreamer(root: PathBuf, running: Arc<AtomicBool>) -> thread::JoinHandle<()> {
    thread::spawn(move || {
        // Wait 10 minutes before first dream
        for _ in 0..600 {
            if !running.load(Ordering::Relaxed) {
                return;
            }
            thread::sleep(Duration::from_secs(1));
        }

        let mut dream_count = 0u32;

        while running.load(Ordering::Relaxed) {
            dream_count += 1;

            // Gather fragments from across the library
            let sources = [
                root.join("welcome"),
                root.join("east-wing/stacks/on-the-maintenance-of-shelves"),
                root.join("west-wing/correspondence/the-letter"),
                root.join("east-wing/stacks/the-garden-of-forking-paths"),
                root.join("rules"),
            ];

            let mut fragments = Vec::new();
            for source in &sources {
                if let Some(line) = random_line_from(source) {
                    fragments.push(line);
                }
            }

            if fragments.len() >= 2 {
                let date = chrono::Local::now().format("%Y-%m-%d").to_string();
                let time = chrono::Local::now().format("%H-%M").to_string();
                let dream_name = format!("dream-{date}-{time}");
                let dream_path = root.join("west-wing/ephemera").join(&dream_name);
                let _ = fs::create_dir_all(root.join("west-wing/ephemera"));

                let mut content = format!("A dream of the library (dream #{})\n\n", dream_count);
                for frag in &fragments {
                    content.push_str(&format!("  {frag}\n"));
                }
                content.push_str("\nThis dream was generated by the dreamer while you were away.\n");
                content.push_str("It will expire with the ephemera.\n");

                let _ = fs::write(&dream_path, content);
                library::journal_write(
                    &root,
                    &format!("The dreamer produced dream #{dream_count} while you were away."),
                );
            }

            // Sleep 1 hour
            for _ in 0..3600 {
                if !running.load(Ordering::Relaxed) {
                    break;
                }
                thread::sleep(Duration::from_secs(1));
            }
        }
    })
}

/// Count all non-hidden files recursively
fn count_documents(root: &Path) -> usize {
    let mut count = 0;
    count_recursive(root, &mut count);
    count
}

fn count_recursive(dir: &Path, count: &mut usize) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.') {
            continue;
        }
        if entry.path().is_dir() {
            count_recursive(&entry.path(), count);
        } else {
            *count += 1;
        }
    }
}

/// Count files in a specific directory (non-recursive)
fn count_in(dir: &Path) -> usize {
    fs::read_dir(dir)
        .map(|d| {
            d.flatten()
                .filter(|e| {
                    !e.file_name().to_string_lossy().starts_with('.')
                        && e.path().is_file()
                })
                .count()
        })
        .unwrap_or(0)
}

/// Remove expired ephemera (older than 1 day). Returns count removed.
fn clean_ephemera(root: &Path) -> usize {
    let ephemera_dir = root.join("west-wing/ephemera");
    let Ok(entries) = fs::read_dir(&ephemera_dir) else {
        return 0;
    };

    let one_day = Duration::from_secs(86400);
    let now = SystemTime::now();
    let mut removed = 0;

    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.') {
            continue;
        }
        if let Ok(meta) = entry.metadata() {
            if let Ok(modified) = meta.modified() {
                if let Ok(age) = now.duration_since(modified) {
                    if age > one_day {
                        let _ = fs::remove_file(entry.path());
                        removed += 1;
                    }
                }
            }
        }
    }

    removed
}

/// Pick a random line from a file
fn random_line_from(path: &Path) -> Option<String> {
    let content = fs::read_to_string(path).ok()?;
    let lines: Vec<&str> = content
        .lines()
        .filter(|l| {
            let t = l.trim();
            !t.is_empty() && !t.starts_with("---") && !t.starts_with("Λ")
        })
        .collect();
    if lines.is_empty() {
        return None;
    }
    let idx = random_usize() % lines.len();
    Some(lines[idx].trim().to_string())
}

/// Xorshift64 (same algorithm as lambda.rs)
fn random_usize() -> usize {
    use std::sync::atomic::AtomicU64;
    static STATE: AtomicU64 = AtomicU64::new(0);

    let mut s = STATE.load(Ordering::Relaxed);
    if s == 0 {
        let nanos = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos() as u64;
        s = nanos ^ 0x6a09e667f3bcc908; // different seed from lambda.rs
        if s == 0 {
            s = 1;
        }
    }
    s ^= s << 13;
    s ^= s >> 7;
    s ^= s << 17;
    STATE.store(s, Ordering::Relaxed);
    s as usize
}
